%% to get a better feel for some of the patterns in the Fruend data,
% compare the weights generated by their model with a more basic logistic
% regression model at lag 1

close all; clc; clear;
load('~/Data/UvA_pupil/GrandAverage/historyMatlab.mat'); % my own weights
load('~/Data/UvA_pupil/GrandAverage/historyweights.mat'); % python weights

mlIdx = {[3 3], [3 4], [3 6], [3 7], [1 3], [1 4], [2 3], [2 4]};
pyFld = {'response', 'response_pupil', 'stimulus', 'stimulus_pupil', 'incorrect', 'incorrect_pupil', 'correct', 'correct_pupil'};

for sp = 1:length(mlIdx),
    subplot(4,4,sp);
    plot(squeeze(grandavg.betas(:, mlIdx{sp}(1), mlIdx{sp}(2))), ...
        dat.(pyFld{sp})(:, 1), 'o', 'MarkerFaceColor', 'k', 'MarkerEdgeColor', 'w');
    box off;
    axis image;
    title(pyFld{sp}, 'interpreter', 'none');
    
    hold on;
    xlims = get(gca, 'xlim');
    plot(xlims, xlims, 'b');
end

suplabel('Matlab', 'x'); suplabel('Python', 'y');
print(gcf, '-dpdf', sprintf('~/Dropbox/Figures/serial/MatlabPythonComparison.pdf'));
